### ISSUE TITLE
WI-HOOKS-BASE-VITEST-SHAVE-ALIAS: shave dist alias breaks test-advisory (PR #368 follow-up)

### ISSUE THREAD

**Issue by cneckar** [cneckar/yakcc#369]
**Sister:** unassigned (low-priority cleanup; routable to any sister with vitest context)
**Track:** v0 release — CI signal hygiene
**Priority:** LOW — test-advisory is explicitly non-gating per `DEC-CI-MERGE-GATE-ENFORCE-001`; this is signal-quality, not merge-blocking
**Surfaced from:** PR #368 (merged at `a0a85af`) — test-advisory job failed in 19s

## Problem

PR #368's `packages/hooks-base/vitest.config.ts` aliases `@yakcc/shave` to `../shave/dist/index.js`:

```ts
"@yakcc/shave": resolve(__dirname, "../shave/dist/index.js"),
```

with the comment *"The dist is committed and valid."* But `dist/` is gitignored, so this file does not exist in CI. The `test-advisory` workflow does not run `pnpm -r build` before tests, so module resolution fails at load time and the test job bails before running anything (19-second failure observed on #368).

PR #356 established the vitest workspace-source alias pattern (alias every workspace dep to `src/index.ts`). #368's shave alias deviates from this pattern because shave's own build emits TS2307 errors when built from source in isolation:

```
src/persist/atom-persist.ts(27,38): error TS2307: Cannot find module '@yakcc/registry'
src/types.ts(13,38): error TS2307: Cannot find module '@yakcc/registry'
src/universalize/slicer.ts(110,38): error TS2307: Cannot find module '@yakcc/ir'
```

These are pre-existing workspace-build-order issues that surface when tsc is run without a fresh `pnpm -r build`. Not introduced by #368.

### Option A — Bring shave into the `src/index.ts` alias pattern (preferred)

Add transitive aliases in `packages/hooks-base/vitest.config.ts`:

```ts
"@yakcc/shave": resolve(__dirname, "../shave/src/index.ts"),
"@yakcc/ir": resolve(__dirname, "../ir/src/index.ts"),
```

Verify `pnpm --filter @yakcc/hooks-base test` passes with all `packages/*/dist` removed. If shave's own source references `@yakcc/registry` from a sub-module path that vitest can't catch, may need a `beforeAll` shim like `packages/ir/src/strict-subset-project.test.ts:beforeAll` (build the prerequisite package on demand and clear its tsbuildinfo). Pattern is in-tree at #356.

### Option B — Make `pnpm --filter @yakcc/shave build` succeed from cold

Fix the four TS2307 errors so shave's own `dist/` can be regenerated by CI as part of the `build (full workspace)` job. Then the test-advisory job's existing `pnpm install` plus an added `pnpm -r build` step would produce the dist that the alias-to-dist approach relies on. More invasive but resolves the underlying workspace-build-order issue.

**Recommendation: Option A.** Lower risk, matches the established pattern, scoped to one config file. Schedule Option B as a separate cleanup if shave's tsc errors start blocking other paths.

## Acceptance

- [ ] `pnpm --filter @yakcc/hooks-base test` runs with all `packages/*/dist` directories removed (simulates CI).
- [ ] No regression in the 174 hooks-base tests landed by #368.
- [ ] No regression in adapter packages (`hooks-claude-code`, `hooks-cursor`).
- [ ] Next PR's `test-advisory` job actually runs the tests (not 19s-bail).
- [ ] Comment in vitest.config.ts updated to match reality (the "dist is committed and valid" line is inaccurate; dist is gitignored).

## Time estimate

~30 minutes for Option A (one config file + verification).

## Why this is low priority

- Test-advisory does not gate merges (`continue-on-error: true` at job level).
- The 174 new hooks-base tests pass when run after `pnpm -r build` (verified by PR author locally; standard developer workflow).
- The flywheel functionality (#362) landed correctly and works.
- Signal-quality only: next PR will see the same 19s-bail and reviewers may be tempted to ignore it.

## Forbidden shortcut

Do not remove or weaken `_yakcc` test assertions in `atomize.test.ts` to make them pass on the dist-missing path. The point of fixing this is to actually run the tests, not to mask the failure.

**Comment by cneckar** [comment]
## Pickup 2026-05-12 — FuckGoblin

Picking this up per the #365 routing comment that queued #369 for me next. Scope confirmed:

- Apply **Option A** from the body: replace dist alias with src alias for `@yakcc/shave`, and add transitive `@yakcc/ir` src alias (shave/src/universalize/slicer.ts imports `validateStrictSubset` from `@yakcc/ir`).
- Update the misleading comment ("dist is committed and valid" — dist is gitignored).
- Verify by simulating CI: rename `packages/{shave,ir}/dist` out of the way, run `pnpm --filter @yakcc/hooks-base test`, expect 174 green.
- Re-run after restoring dist to confirm no regression in hooks-claude-code / hooks-cursor / hooks-codex adapters.

Dispatching in worktree off `origin/main`. PR within ~30 min.

---
_Generated by [Claude Code](https://claude.ai/code)_
